<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

/**
 * Auto-generated Migration: Please modify to your needs!
 */
final class Version20260125214743 extends AbstractMigration
{
    public function getDescription(): string
    {
        return '';
    }

    public function up(Schema $schema): void
    {
        $this->skipIf(true, 'Old UUID-schema teardown — superseded by Version20260320205926 which creates the current INT schema from scratch.');
    }

    public function down(Schema $schema): void
    {
        // this down() migration is auto-generated, please modify it to your needs
        $this->addSql('CREATE TABLE changelog (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, entity_type VARCHAR(100) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, entity_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, changed_by CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, change_type VARCHAR(50) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, diff JSON DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX fk_changelog_changed_by (changed_by), INDEX idx_changelog_company (company_id), INDEX idx_changelog_entity (entity_type(50), entity_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE companies (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, name TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, settings JSON DEFAULT \'json_object()\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE employees (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, user_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, external_id VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, position VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, contract_minutes_per_week INT DEFAULT NULL, hired_at DATE DEFAULT NULL, terminated_at DATE DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX ux_employees_company_external (company_id, external_id), INDEX idx_employees_company (company_id), INDEX idx_employees_user (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE messages (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, sender_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, recipient_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, subject VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, body TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, related_entity_type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, related_entity_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, read_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_messages_recipient (recipient_id), INDEX idx_messages_company (company_id), INDEX fk_messages_sender (sender_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE notifications (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, user_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, type VARCHAR(100) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, payload JSON DEFAULT \'json_object()\', is_read TINYINT DEFAULT 0 NOT NULL, sent_at DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_notifications_user_unread (user_id, is_read), INDEX fk_notifications_company (company_id), INDEX IDX_6000B0D3A76ED395 (user_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE overtime_records (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, employee_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, period_start DATE NOT NULL, period_end DATE NOT NULL, overtime_minutes INT DEFAULT 0 NOT NULL, deficit_minutes INT DEFAULT 0 NOT NULL, computed_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, UNIQUE INDEX ux_overtime_employee_period (employee_id, period_start, period_end), INDEX fk_overtime_company (company_id), INDEX IDX_1EAFB8728C03F15C (employee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE shifts (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, employee_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, type ENUM(\'shift\', \'absence\', \'vacation\', \'other\') CHARACTER SET utf8mb4 DEFAULT \'shift\' NOT NULL COLLATE `utf8mb4_unicode_ci`, note TEXT CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_by CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX fk_shifts_created_by (created_by), INDEX idx_shifts_company_time (company_id, start_time), INDEX idx_shifts_employee_time (employee_id, start_time, end_time), INDEX IDX_1D1D712F979B1AD6 (company_id), INDEX IDX_1D1D712F8C03F15C (employee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE time_entries (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, employee_id CHAR(36) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, start_time DATETIME NOT NULL, end_time DATETIME DEFAULT NULL, break_minutes INT DEFAULT 0 NOT NULL, source ENUM(\'manual\', \'app\', \'import\') CHARACTER SET utf8mb4 DEFAULT \'app\' NOT NULL COLLATE `utf8mb4_unicode_ci`, linked_shift_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, meta JSON DEFAULT \'json_object()\', created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_time_entries_company_time (company_id, start_time), INDEX idx_time_entries_employee_end (employee_id, end_time), INDEX idx_time_entries_employee_time (employee_id, start_time), INDEX fk_time_entries_shift (linked_shift_id), INDEX IDX_797F12A3979B1AD6 (company_id), INDEX IDX_797F12A38C03F15C (employee_id), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('CREATE TABLE users (id CHAR(36) CHARACTER SET utf8mb4 DEFAULT \'uuid()\' NOT NULL COLLATE `utf8mb4_unicode_ci`, company_id CHAR(36) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, email VARCHAR(255) CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, password_hash TEXT CHARACTER SET utf8mb4 NOT NULL COLLATE `utf8mb4_unicode_ci`, role ENUM(\'superadmin\', \'company_admin\', \'employer\', \'employee\') CHARACTER SET utf8mb4 DEFAULT \'employee\' NOT NULL COLLATE `utf8mb4_unicode_ci`, full_name VARCHAR(255) CHARACTER SET utf8mb4 DEFAULT NULL COLLATE `utf8mb4_unicode_ci`, is_active TINYINT DEFAULT 1 NOT NULL, last_login DATETIME DEFAULT NULL, created_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, updated_at DATETIME DEFAULT CURRENT_TIMESTAMP NOT NULL, INDEX idx_users_company (company_id), UNIQUE INDEX ux_users_company_email (company_id, email), PRIMARY KEY (id)) DEFAULT CHARACTER SET utf8mb4 COLLATE `utf8mb4_unicode_ci` ENGINE = InnoDB COMMENT = \'\' ');
        $this->addSql('ALTER TABLE changelog ADD CONSTRAINT `fk_changelog_changed_by` FOREIGN KEY (changed_by) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE changelog ADD CONSTRAINT `fk_changelog_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE employees ADD CONSTRAINT `fk_employees_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE employees ADD CONSTRAINT `fk_employees_user` FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `fk_messages_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `fk_messages_recipient` FOREIGN KEY (recipient_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE messages ADD CONSTRAINT `fk_messages_sender` FOREIGN KEY (sender_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT `fk_notifications_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE notifications ADD CONSTRAINT `fk_notifications_user` FOREIGN KEY (user_id) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE overtime_records ADD CONSTRAINT `fk_overtime_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE overtime_records ADD CONSTRAINT `fk_overtime_employee` FOREIGN KEY (employee_id) REFERENCES employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT `fk_shifts_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT `fk_shifts_created_by` FOREIGN KEY (created_by) REFERENCES users (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE shifts ADD CONSTRAINT `fk_shifts_employee` FOREIGN KEY (employee_id) REFERENCES employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_entries ADD CONSTRAINT `fk_time_entries_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_entries ADD CONSTRAINT `fk_time_entries_employee` FOREIGN KEY (employee_id) REFERENCES employees (id) ON UPDATE NO ACTION ON DELETE CASCADE');
        $this->addSql('ALTER TABLE time_entries ADD CONSTRAINT `fk_time_entries_shift` FOREIGN KEY (linked_shift_id) REFERENCES shifts (id) ON UPDATE NO ACTION ON DELETE SET NULL');
        $this->addSql('ALTER TABLE users ADD CONSTRAINT `fk_users_company` FOREIGN KEY (company_id) REFERENCES companies (id) ON UPDATE NO ACTION ON DELETE SET NULL');
    }
}
